(function(){'use strict';
const A=window.AUXY_AUTH,DB=window.AUXY_DB_API,U=window.AUXY_UTIL,UI=window.AUXY_UI,C=window.AUXY_COMPONENTS;
const root=document.querySelector('#app'),state=window.AUXY_STATE.get();(function(){try{const low=(navigator.deviceMemory&&navigator.deviceMemory<=4)||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=4);if(low)document.documentElement.classList.add('auxy-lite')}catch{}})();
const profile=()=>state.profile||state.me;const owner=()=>['ali','auxy','support','rezabzm'].includes(U.username(profile()?.username))||profile()?.role==='owner';const publisher=()=>owner()||profile()?.role==='publisher';
function shell(title,active){document.documentElement.classList.remove('auxy-scroll-mode');root.innerHTML=`<div class="app"><div class="topbar-wrap">${C.topbar(active,title)}</div><main id="view" class="view"></main>${C.bottom(active)}</div>`;root.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>window.AUXY_ROUTER.set(b.dataset.route));return root.querySelector('#view')}
function errorView(v,e){v.innerHTML=`<section class="empty-state glass-card"><div class="empty-icon">${UI.icon('info',25)}</div><h2>بارگذاری انجام نشد</h2><p>${U.esc(e?.message||'خطای ناشناخته')}</p><button class="ios-btn primary" data-retry>تلاش دوباره</button></section>`;v.querySelector('[data-retry]')?.addEventListener('click',()=>window.AUXY_ROUTER.start())}
async function home(){const v=shell('خانه','home');return window.AUXY_SOCIAL.home(v)}
async function ai(){const v=shell('Auxy AI','');return window.AUXY_AI.render(v)}
async function explore(){const v=shell('اکسپلور','explore');return window.AUXY_SOCIAL.explore(v)}
async function scroll(parts){const v=shell('Scroll','scroll');return window.AUXY_SOCIAL.scroll(v,parts[0]||'')}
async function userProfile(parts){const v=shell('پروفایل','profile');return window.AUXY_SOCIAL.profile(v,parts[0]||profile().username)}
async function chat(parts){const v=shell('چت','chat');window.AUXY_CHAT.init(profile());const c=v.querySelector('.chat-shell');if(parts[0]){await window.AUXY_CHAT.open(v,parts[0])}else await window.AUXY_CHAT.list(v)}
function catalogRail(title,items,type){const list=Array.isArray(items)?items:[];if(!list.length)return '';const cards=list.map(x=>type==='series'?C.seriesCard(x):C.movieCard(x)).join('');return `<section class="catalog-section"><div class="section-row"><div><h2>${U.esc(title)}</h2><small class="muted">${U.formatCount(list.length)} عنوان</small></div><div class="rail-actions"><button class="icon-button" data-rail-prev aria-label="قبلی">${UI.icon('chevron-left',18)}</button><button class="icon-button" data-rail-next aria-label="بعدی">${UI.icon('chevron-right',18)}</button></div></div><div class="content-rail"><div class="content-track">${cards}</div></div></section>`}
async function movies(){const v=shell('فیلم و سریال','movies');UI.loading(true,'در حال بارگذاری کتابخانه…');try{const [mv,ss]=await Promise.all([DB.movies(),DB.series()]);const movies=mv||[],series=ss||[],newMovies=movies.filter(x=>x.is_new_release),newSeries=series.filter(x=>x.is_new_release),iranMovies=movies.filter(x=>x.is_iranian),iranSeries=series.filter(x=>x.is_iranian);v.innerHTML=`<div class="page-head"><div><div class="eyebrow">AUXY LIBRARY</div><h1>فیلم و سریال</h1><p>کاتالوگ Auxy؛ مرتب، افقی و بدون شلوغی.</p></div>${publisher()?UI.button('استودیو','route:studio','primary','plus'):''}</div>${catalogRail('جدیدترین‌ها',newMovies.slice(0,18),'movie')}${catalogRail('سریال‌ها و دراماهای جدید',newSeries.slice(0,18),'series')}${catalogRail('سینمای ایران',iranMovies.slice(0,18),'movie')}${catalogRail('درامای ایرانی',iranSeries.slice(0,18),'series')}${catalogRail('فیلم‌ها',movies.slice(0,24),'movie')}${catalogRail('سریال و دراما',series.slice(0,24),'series')}`;v.querySelector('[data-action="route:studio"]')?.addEventListener('click',()=>window.AUXY_ROUTER.set('studio'));wireRails(v);wireMovieClicks(v,movies);wireSeriesClicks(v,series);C.hydrateArtwork?.(v);C.hydrateMovieVisuals?.(v);C.hydrateSeriesVisuals?.(v)}catch(e){errorView(v,e)}finally{UI.loading(false)}}
function wireRails(root){root.querySelectorAll('.catalog-section').forEach(sec=>{const rail=sec.querySelector('.content-rail'),step=rail?.clientWidth?Math.max(rail.clientWidth*.78,320):500;sec.querySelector('[data-rail-prev]')?.addEventListener('click',()=>rail.scrollBy({left:-step,behavior:'smooth'}));sec.querySelector('[data-rail-next]')?.addEventListener('click',()=>rail.scrollBy({left:step,behavior:'smooth'}))})}
function wireMovieClicks(root,movies){root.querySelectorAll('[data-play-movie]').forEach(b=>b.onclick=e=>{e.stopPropagation();const m=movies.find(x=>x.id===b.dataset.playMovie);if(m)window.AUXY_MEDIA.showMovie(m)});root.querySelectorAll('[data-movie-comments]').forEach(b=>b.onclick=e=>{e.stopPropagation();window.AUXY_MEDIA.showMovieComments(b.dataset.movieComments)});root.querySelectorAll('[data-movie-id]').forEach(b=>b.onclick=()=>{const m=movies.find(x=>x.id===b.dataset.movieId);if(m)window.AUXY_MEDIA.showMovie(m)})}
function wireSeriesClicks(root,series){root.querySelectorAll('[data-series-id]').forEach(b=>b.onclick=()=>{const x=series.find(x=>x.id===b.dataset.seriesId);if(x)window.AUXY_MEDIA.showSeries(x)})}
async function search(){const v=shell('جستجو','explore');v.innerHTML=`<div class="search-page"><div class="page-head"><div><div class="eyebrow">SEARCH</div><h1>جستجو</h1><p>کاربر، فیلم، سریال و دراما.</p></div></div><form id="search-form" class="explore-search">${UI.icon('search',19)}<input id="search-input" class="input" placeholder="مثلاً Squid Game یا فیلم ایرانی…"><button class="icon-button" type="submit">${UI.icon('search',18)}</button></form><div id="search-out"></div></div>`;const input=v.querySelector('#search-input'),out=v.querySelector('#search-out');const run=async()=>{const q=input.value.trim();if(q.length<2){out.innerHTML='';return}try{const [users,items]=await Promise.all([DB.searchProfiles(q),DB.searchCatalog(q,24)]);const movies=(items||[]).filter(x=>(x.media_type||x.content_type||'movie')==='movie');const series=(items||[]).filter(x=>x.media_type==='series'||x.content_kind==='series');out.innerHTML=`${users?.length?`<section class="search-section"><h2>کاربران</h2><div class="list">${users.map(u=>`<a class="list-row glass-card" href="#/profile/${U.esc(u.username)}">${UI.avatar(u,44)}${C.identity(u)}</a>`).join('')}</div></section>`:''}${catalogRail('فیلم‌های مرتبط',movies,'movie')}${catalogRail('سریال و دراما',series,'series')}${!movies.length&&!series.length&&!users.length?'<div class="empty-state">چیزی پیدا نشد.</div>':''}`;wireRails(out);wireMovieClicks(out,movies);wireSeriesClicks(out,series);C.hydrateMovieVisuals?.(out);C.hydrateSeriesVisuals?.(out)}catch(e){UI.toast(e.message,'error')}};v.querySelector('#search-form').onsubmit=e=>{e.preventDefault();run()};input.oninput=U.debounce(run,350)}

async function subscription(){const v=shell('بزودی','profile');v.innerHTML='<section class="empty-state glass-card coming-soon-card"><div class="empty-icon">'+UI.icon('clock',25)+'</div><h2>بزودی</h2><button class="ios-btn" data-coming-soon>به‌زودی</button></section>';v.querySelector('[data-coming-soon]')?.addEventListener('click',()=>UI.toast('به‌زودی فعال می‌شود.','info'))}
async function auso(){return subscription()}
async function creatorAnalytics(){const v=shell('Creator Pro','profile');const sub=await window.AUXY_SUBS.meSub();if(!sub?.active){return window.AUXY_SUBS.load(v)}return window.AUXY_SUBS.analytics(v,profile())}
async function support(){const v=shell('پشتیبانی','profile');v.innerHTML=`<div class="page-head"><div><div class="eyebrow">SUPPORT</div><h1>پشتیبانی</h1><p>درخواستت را مستقیماً برای تیم Auxy ثبت کن.</p></div></div><section class="glass-card support-card"><div class="support-status"><span class="online-dot"></span><div><b>Support</b><small>آنلاین</small></div></div><textarea id="support-text" class="textarea" maxlength="50000" placeholder="موضوع یا درخواست…"></textarea>${UI.button('ارسال درخواست','send-support','primary','send')}</section>`;v.querySelector('[data-action="send-support"]').onclick=async()=>{const text=v.querySelector('#support-text')?.value.trim();if(!text)return UI.toast('متن درخواست را وارد کن.','error');try{const r=await DB.client.rpc('auxy_create_ticket',{p_subject:'Auxy Support',p_body:text});if(r.error)throw r.error;v.querySelector('#support-text').value='';UI.toast('درخواست ارسال شد.','success')}catch(e){UI.toast(e.message||'ثبت تیکت انجام نشد.','error')}}}
async function notifications(){const v=shell('اعلان‌ها','profile');UI.loading(true,'در حال دریافت اعلان‌ها…');try{const n=await DB.notifications(profile().id);v.innerHTML=`<div class="page-head"><div><div class="eyebrow">ACTIVITY</div><h1>اعلان‌ها</h1><p>دنبال‌کردن، لایک، نظر، ریپوست و پیام‌های جدید اینجا جمع می‌شوند.</p></div><button class="ios-btn" data-read-all>${UI.icon('check',16)}خواندن همه</button></div><div class="notification-list">${(n||[]).map(x=>{const unread=!x.read_at;const msg=x.message||x.reason||x.data?.message||x.payload?.message||'رویداد جدید';return `<article class="notification-card glass-card ${unread?'unread':''}"><span class="notif-icon">${UI.icon(x.type==='follow'?'user':x.type==='like'?'heart':x.type==='comment'?'comment':x.type==='message'?'chat':'bell',20)}</span><div class="grow"><b>${U.esc(x.type==='follow'?'دنبال‌کننده جدید':x.type==='like'?'لایک جدید':x.type==='comment'?'نظر جدید':x.type==='message'?'پیام جدید':'اعلان Auxy')}</b><p>${U.esc(msg)}</p><small>${U.esc(U.ago(x.created_at))}</small></div></article>`}).join('')||'<div class="empty-state glass-card">اعلانی نیست.</div>'}</div>`;v.querySelector('[data-read-all]')?.addEventListener('click',async()=>{try{await DB.markNotificationsRead();UI.toast('همه اعلان‌ها خوانده شد.','success');await notifications()}catch(e){UI.toast(e.message,'error')}});if(DB.markNotificationsRead)await DB.markNotificationsRead();updateNotifCount(0)}catch(e){errorView(v,e)}finally{UI.loading(false)}}
function updateNotifCount(n){document.querySelectorAll('[data-notif-count]').forEach(e=>{const x=Number(n)||0;e.textContent=x>99?'99+':String(x);e.classList.toggle('hidden',x<1)})}
async function refreshNotifCount(){try{const n=await DB.notificationsUnread();updateNotifCount(n)}catch{}}

window.AUXY_ROUTER.on('home',home);window.AUXY_ROUTER.on('ai',ai);window.AUXY_ROUTER.on('community',community);window.AUXY_ROUTER.on('invite',invite);window.AUXY_ROUTER.on('explore',explore);window.AUXY_ROUTER.on('scroll',scroll);window.AUXY_ROUTER.on('profile',userProfile);window.AUXY_ROUTER.on('u',userProfile);window.AUXY_ROUTER.on('chat',chat);window.AUXY_ROUTER.on('movies',movies);window.AUXY_ROUTER.on('settings',settings);window.AUXY_ROUTER.on('owner',ownerPanel);window.AUXY_ROUTER.on('studio',studio);window.AUXY_ROUTER.on('search',search);window.AUXY_ROUTER.on('support',support);window.AUXY_ROUTER.on('notifications',notifications);window.AUXY_ROUTER.on('subscription',subscription);window.AUXY_ROUTER.on('auso',auso);window.AUXY_ROUTER.on('creator-analytics',creatorAnalytics);window.addEventListener('message',e=>{if(e.data?.type!=='AUXY_REMOTE_KEY')return;const key=e.data.key;if(key==='Escape'){history.back();return}const els=[...document.querySelectorAll('button:not([disabled]),a[href],input,select,textarea')].filter(x=>{const r=x.getBoundingClientRect();return r.width>0&&r.height>0&&getComputedStyle(x).visibility!=='hidden'});if(!els.length)return;let i=els.indexOf(document.activeElement);if(i<0)i=0;if(key==='ArrowDown'||key==='ArrowRight')i=Math.min(els.length-1,i+1);if(key==='ArrowUp'||key==='ArrowLeft')i=Math.max(0,i-1);if(key==='Enter'){els[i]?.click?.();return}els[i]?.focus?.();els[i]?.classList.add('auxy-tv-focus');setTimeout(()=>els[i]?.classList.remove('auxy-tv-focus'),700)});
(async()=>{try{const s=await A.session();if(!s){location.replace('/login/');return}state.session=s;state.profile=await A.profile();state.me=state.profile;if(!state.profile?.username){location.replace('/login/#signup');return}window.AUXY_STATE.patch({session:s,user:s.user||null,profile:state.profile,me:state.profile});window.AUXY_SOCIAL.init(state.profile);refreshNotifCount();try{const ch=DB.subscribeNotifications?.(state.profile.id,e=>{updateNotifCount((Number(document.querySelector('[data-notif-count]')?.textContent)||0)+1);const m=e.new?.message||'اعلان جدید داری.';UI.toast(m,'info','اعلان Auxy')});window.__AUXY_NOTIF_CH=ch}catch{}await window.AUXY_ROUTER.start()}catch(e){root.innerHTML=`<section class="empty-state glass-card app-fatal"><div class="empty-icon">${UI.icon('info',24)}</div><h2>Auxy آماده نشد</h2><p>${U.esc(e.message)}</p><button class="ios-btn primary" onclick="location.reload()">تلاش دوباره</button></section>`}})();
})();
