(function(){'use strict';
const U=window.AUXY_UTIL,UI=window.AUXY_UI;
function verificationType(p){const n=String(p?.username||'').toLowerCase(),role=String(p?.role||'user').toLowerCase();if(n==='rezabzm'&&role==='user')return'blue';if(n==='ali')return'blue';if(n==='support'||n==='auxy')return'gold';return p?.verified_type||null}
function badge(p){const t=verificationType(p),n=String(p?.username||'').toLowerCase();const management=['ali','auxy','support','rezabzm'].includes(n);const auxyMark=management?'<span class="identity-logo-mark" data-verify="auxy" role="button" tabindex="0" aria-label="لوگوی رسمی Auxy"><img src="/assets/auxy-white.png" alt="Auxy"></span>':'';const y=n==='rezabzm'&&t==='blue'?'<span class="identity-logo-mark yektanet-click" data-verify="yektanet" role="button" tabindex="0" aria-label="نشان یکتانت"><img class="yektanet-mark" src="/assets/yektanet.svg" alt="Yektanet"></span>':'';const blue='<span class="identity-badge blue" data-verify="blue" role="button" tabindex="0" aria-label="تیک آبی Auxy"><svg viewBox="0 0 24 24"><path d="M12 2.8 14.6 4l2.8-.2 1.3 2.5 2.4 1.8-.8 2.8.8 2.8-2.4 1.8-1.3 2.5-2.8-.2-2.6 1.2-2.6-1.2-2.8.2-1.3-2.5-2.4-1.8.8-2.8-.8-2.8 2.4-1.8L6.1 3.8l2.8.2z"/><path d="m8.3 12.1 2.4 2.4 4.9-5.1"/></svg></span>';const gold='<span class="identity-badge gold" data-verify="gold" role="button" tabindex="0" aria-label="تیک طلایی Auxy"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="9"/><path d="m8.1 12.1 2.5 2.5 5.4-5.3"/></svg></span>';if(t==='blue')return blue+y+auxyMark;if(t==='gold')return gold+auxyMark;return auxyMark}
function identity(p,sub=true){return `<span class="identity"><b>${U.esc(p?.display_name||p?.username||'کاربر')} ${badge(p)}</b>${sub?`<small dir="ltr">@${U.esc(p?.username||'')}</small>`:''}</span>`}
function bindVerification(root){const r=root||document;r.querySelectorAll('[data-verify]').forEach(el=>{if(el.dataset.bound==='1')return;el.dataset.bound='1';el.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();showVerification(el.dataset.verify||'blue')})});return r}
function showVerification(type){const t=String(type||'').toLowerCase();const title=t==='blue'?'تیک آبی Auxy':t==='gold'?'تیک طلایی Auxy':t==='auxy'?'نشان رسمی Auxy':t==='yektanet'?'نشان یکتانت':'نشان Auxy';const desc=t==='blue'?'نشان تأیید آبی برای شناسایی حساب تأییدشده Auxy است.':t==='gold'?'نشان طلایی هویت رسمی حساب‌های مدیریت Auxy را مشخص می‌کند.':t==='auxy'?'لوگوی کوچک Auxy نشان رسمی برند را کنار هویت حساب نشان می‌دهد.':t==='yektanet'?'این نشان ارتباط رسمی حساب rezabzm با یکتانت را نمایش می‌دهد.':'این نشان بخشی از سیستم هویت Auxy است.';const icon=t==='auxy'?'<img class="verify-auxy" src="/assets/auxy-white.png" alt="Auxy">':t==='yektanet'?'<img class="yektanet-mark big" src="/assets/yektanet.svg" alt="Yektanet">':`<span class="identity-badge ${t==='blue'?'blue':'gold'}">${t==='blue'?'✓':'✓'}</span>`;UI.modal({title,content:`<div class="verify-dialog"><div class="verify-symbol">${icon}</div><h3>${title}</h3><p>${U.esc(desc)}</p></div>`,actions:[{label:'متوجه شدم',kind:'primary'}]})}
function topbar(active,title){return `<header class="topbar glass-card"><button class="brand-link" data-route="home" aria-label="Auxy"><img src="/assets/auxy-wordmark-white.png" alt="Auxy"></button><div class="top-title">${U.esc(title||'')}</div><div class="top-actions"><button class="icon-button ai-top-btn" data-route="ai" aria-label="Auxy AI">${UI.icon('sparkles',18)}</button><button class="icon-button notif-top-btn" data-route="notifications" aria-label="اعلان‌ها">${UI.icon('bell',18)}<span class="notif-count hidden" data-notif-count></span></button><button class="icon-button" data-route="search" aria-label="جستجو">${UI.icon('search',18)}</button><button class="icon-button" data-route="settings" aria-label="تنظیمات">${UI.icon('settings',18)}</button></div></header>`}
function bottom(active){const items=[['home','خانه','home'],['explore','اکسپلور','grid'],['scroll','Scroll','play'],['chat','چت','chat'],['movies','فیلم و سریال','library'],['profile','پروفایل','user']];return `<nav class="bottom-nav glass-card" aria-label="ناوبری اصلی">${items.map(([r,t,i])=>`<button type="button" class="bottom-item ${active===r?'active':''}" data-route="${r}"><span>${UI.icon(i,19)}</span><small>${t}</small></button>`).join('')}</nav>`}
function shell(title,active){return topbar(active,title)+`<main id="view" class="view"></main>`+bottom(active)}
function postCard(p,u,opts={}){const liked=!!opts.liked,saved=!!opts.saved,reposted=!!opts.reposted;return `<article class="post-card glass-card" data-post-id="${U.esc(p.id)}"><header class="post-user"><a class="post-user-link" href="#/profile/${U.esc(u?.username||'')}">${UI.avatar(u,46)}${identity(u)}</a><time>${U.esc(U.ago(p.created_at))}</time></header>${p.media_url?`<div class="post-media-wrap">${p.kind==='video'?`<video class="post-media lazy-media" src="${U.esc(p.media_url)}" poster="${U.esc(p.poster_url||'')}" controls playsinline preload="metadata"></video>`:`<img class="post-media" src="${U.esc(p.media_url)}" alt="" loading="lazy">`}</div>`:''}${p.caption?`<div class="post-body emoji-text">${UI.emojiText(p.caption)}</div>`:''}<div class="post-actions"><button class="action-button like-btn ${liked?'on':''}" data-like-post="${U.esc(p.id)}">${UI.icon('heart',18,liked)}<span>${U.formatCount(p.likes_count)}</span></button><button class="action-button" data-comment-post="${U.esc(p.id)}">${UI.icon('comment',18)}<span>${U.formatCount(p.comments_count)}</span></button><span class="action-button passive-stat">${UI.icon('eye',18)}<span>${U.formatCount(p.views_count)}</span></span><button class="action-button ${saved?'on':''}" data-save-post="${U.esc(p.id)}">${UI.icon('bookmark',18,saved)}</button><button class="action-button ${reposted?'on':''}" data-repost-post="${U.esc(p.id)}">${UI.icon('repost',18,reposted)}</button><button class="action-button" data-share-post="${U.esc(p.id)}">${UI.icon('share',18)}</button><button class="action-button" data-copy-post="${U.esc(p.id)}">${UI.icon('copy',18)}</button><button class="action-button" data-report-post="${U.esc(p.id)}" aria-label="گزارش">${UI.icon('flag',18)}</button></div></article>`}
function movieCard(m){const playable=!!(m.video_url_en||m.video_url_fa||m.video_url||m.archive_id);const poster=m.poster_url||m.safe_poster_url||m.poster;const img=poster?`<img data-movie-poster src="${U.esc(poster)}" alt="پوستر ${U.esc(m.title)}" loading="lazy">`:`<img data-movie-poster src="" alt="پوستر ${U.esc(m.title)}" loading="lazy">`;return `<article class="movie-card" data-movie-id="${U.esc(m.id)}" data-imdb-id="${U.esc(m.imdb_id||'')}" data-art-title="${U.esc(m.metadata_search_title||m.title||'')}" data-art-type="movie" data-art-backdrop="${U.esc(m.banner_url||'')}"><div class="movie-poster">${img}<div class="movie-fallback layered-fallback">${UI.icon('video',23)}</div><span class="movie-kind">${U.esc(m.kind||'فیلم')}</span><button class="movie-play-overlay ${playable?'':'unavailable'}" data-play-movie="${U.esc(m.id)}" aria-label="${playable?'پخش فیلم':'باز کردن فیلم'}">${UI.icon('play',25,true)}</button></div><div class="movie-meta"><b>${U.esc(m.title)}</b><small>${U.esc(m.year||'')} ${m.runtime_minutes?'· '+U.esc(m.runtime_minutes)+' دقیقه':''} ${m.imdb_rating?'· IMDb '+U.esc(m.imdb_rating):''}</small><div class="movie-stats"><span>${UI.icon('eye',14)}${U.formatCount(m.views_count)}</span><button type="button" class="movie-comment-link" data-movie-comments="${U.esc(m.id)}">${UI.icon('comment',14)}${U.formatCount(m.comments_count)}</button></div></div></article>`}
function seriesCard(s){const playable=!!(s.video_url||s.archive_id);const poster=s.poster_url||'';return `<article class="series-card" data-series-id="${U.esc(s.id)}" data-art-title="${U.esc(s.metadata_search_title||s.title||'')}" data-art-type="series" data-art-backdrop="${U.esc(s.banner_url||'')}"><div class="series-poster">${poster?`<img data-series-poster src="${U.esc(poster)}" alt="پوستر ${U.esc(s.title)}" loading="lazy">`:`<img data-series-poster src="" alt="پوستر ${U.esc(s.title)}" loading="lazy">`}<div class="movie-fallback layered-fallback">${UI.icon('library',23)}</div><span class="movie-kind">سریال</span></div><div class="series-card-meta"><b>${U.esc(s.title)}</b><small>${U.esc(s.year||'')} ${s.release_status==='ongoing'?'· در حال پخش':''}</small></div></article>`}
async function hydrateArtwork(root){const r=root||document;const els=[...r.querySelectorAll('[data-art-title]')];const seen=new Set();for(const el of els){const key=el.dataset.artTitle+'|'+el.dataset.artType;if(seen.has(key))continue;seen.add(key);const directBackdrop=el.dataset.artBackdrop||'';if(directBackdrop)el.style.setProperty('--movie-backdrop',`url("${directBackdrop}")`);const img=el.querySelector(el.dataset.artType==='series'?'[data-series-poster]':'[data-movie-poster]');const needRemote=!directBackdrop||!img?.getAttribute('src');if(!needRemote)continue;try{const u=`/api/artwork?type=${encodeURIComponent(el.dataset.artType)}&title=${encodeURIComponent(el.dataset.artTitle)}`;const res=await fetch(u,{credentials:'same-origin'});if(!res.ok)continue;const d=await res.json();if(img&&!img.getAttribute('src')&&d.poster)img.src=d.poster;if(d.background&&!directBackdrop)el.style.setProperty('--movie-backdrop',`url("${d.background}")`);if(img&&img.getAttribute('src'))img.classList.add('art-loaded')}catch(_){}}return r}
async function hydrateMovieVisuals(root){return hydrateArtwork(root)}
async function hydrateSeriesVisuals(root){return hydrateArtwork(root)}
function memberCard(u,kind='member'){return `<div class="member-card glass-box">${UI.avatar(u,44)}${identity(u)}<span class="pill">${U.esc(kind)}</span></div>`}
window.AUXY_COMPONENTS={topbar,bottom,shell,postCard,movieCard,seriesCard,hydrateMovieVisuals,hydrateSeriesVisuals,memberCard,identity,badge,bindVerification,showVerification,verificationType};
})();
