(function(){'use strict';
const COMMON=['😀','😃','😄','😁','😆','😅','😂','🤣','😊','😇','🙂','🙃','😉','😍','🥰','😘','😎','🤩','🥳','😭','😡','🤯','😱','🤔','🫡','😴','🤢','🤮','🤠','😈','👻','💀','🤖','❤️','🩷','🧡','💛','💚','🩵','💙','💜','🖤','🤍','🤎','💯','💥','✨','⭐','🔥','⚡','🎉','🎊','🎁','🏆','👍','👎','👌','✌️','🤞','🤟','🤘','🤙','👈','👉','👆','👇','☝️','✋','👏','🙌','🫶','🙏','🤝','💪','👀','🫂','👋','🤌','💅','👶','🧑','👨','👩','🐶','🐱','🦊','🐻','🐼','🐯','🦁','🐷','🐸','🐵','🐔','🐧','🐦','🦄','🐝','🦋','🐢','🐍','🦖','🐙','🦑','🦀','🐠','🐟','🐡','🦈','🐳','🐋','🐬','🦅','🦉','🐺','🐗','🦌','🐘','🦒','🍎','🍊','🍋','🍌','🍉','🍇','🍓','🫐','🍒','🍑','🥭','🍍','🥝','🍕','🍔','🍟','🍿','🍣','🍱','🍜','🍰','🧁','🍪','🍩','🍫','🍭','☕','🧋','⚽','🏀','🏈','⚾','🎾','🎮','🎲','🎧','🎤','🎸','🎹','🎬','🎨','📸','📱','💻','⌚','💡','📚','✏️','📝','🔒','🔑','🔔','📍','✅','❌','❗','❓','⭕','➕','➖','✖️','➗','♻️','☑️','✔️','™️','©️','®️'];
const ALL=Array.from(new Set([...(window.AUXY_EMOJI_ALL||[]),...COMMON]));
const esc=v=>window.AUXY_UTIL.esc(v), normalize=v=>String(v??'').normalize('NFC');
const EMOJI_RE=(() => { try{return /\p{Extended_Pictographic}/u}catch{return null} })();
function isEmoji(g){if(!g)return false;try{return EMOJI_RE?.test(g)||/^[#*0-9]\uFE0F?\u20E3$/u.test(g)||(/^\p{Regional_Indicator}{2}$/u.test(g));}catch{return false}}
function glyph(g,cls='emoji-glyph'){return `<span class="${cls}" role="img" aria-label="${esc(g)}">${esc(g)}</span>`}
function renderText(text){const s=normalize(text),parts=[];try{const seg=new Intl.Segmenter(undefined,{granularity:'grapheme'});for(const x of seg.segment(s)){const t=x.segment;parts.push(isEmoji(t)?glyph(t):esc(t));}}catch{return esc(s)}return parts.join('')}
function img(e,cls='emoji-option'){return glyph(e,cls)}
function close(pop){pop?.remove()}
function pick(emoji,cb,pop){const e=normalize(emoji).trim();if(!e)return;cb(e);try{const st=window.AUXY_STATE.get();const r=Array.from(new Set([e,...(st.emojiRecent||[])])).slice(0,24);window.AUXY_STATE.patch({emojiRecent:r})}catch{}close(pop)}
function openPicker(anchor,cb){close(document.querySelector('.auxy-emoji-pop'));const pop=document.createElement('div');pop.className='auxy-emoji-pop glass-card';pop.innerHTML=`<div class="emoji-head"><b>ایموجی</b><button type="button" class="icon-button emoji-close" aria-label="بستن">${window.AUXY_UI.icon('close',17)}</button></div><div class="emoji-search-row"><input class="input emoji-search" placeholder="جستجوی ایموجی…"><button type="button" class="icon-button emoji-direct-send" aria-label="افزودن ایموجی">${window.AUXY_UI.icon('plus',17)}</button></div><div class="emoji-grid"></div>`;document.body.appendChild(pop);pop.querySelector('.emoji-close').onclick=()=>close(pop);const grid=pop.querySelector('.emoji-grid'),q=pop.querySelector('.emoji-search');let rendered=0;let activeList=[];
const renderChunk=()=>{const start=rendered,end=Math.min(start+180,activeList.length);if(start>=end)return;const frag=document.createDocumentFragment();for(let i=start;i<end;i++){const b=document.createElement('button');b.type='button';b.className='emoji-opt';b.dataset.emoji=activeList[i];b.setAttribute('aria-label',activeList[i]);b.innerHTML=img(activeList[i]);frag.appendChild(b)}grid.appendChild(frag);rendered=end};
const prepare=()=>{const term=q.value.trim();const recent=window.AUXY_STATE?.get?.().emojiRecent||[];activeList=term?[...ALL].filter(e=>e.includes(term)):[...new Set([...recent,...COMMON,...ALL])];rendered=0;grid.innerHTML='';renderChunk();};
prepare();grid.addEventListener('scroll',()=>{if(grid.scrollTop+grid.clientHeight>=grid.scrollHeight-120)renderChunk()});q.oninput=prepare;grid.addEventListener('click',e=>{const b=e.target.closest('[data-emoji]');if(b)pick(b.dataset.emoji,cb,pop)});pop.querySelector('.emoji-direct-send').onclick=()=>{const v=q.value.trim();if(v&&isEmoji(v))pick(v,cb,pop)};const r=anchor.getBoundingClientRect();pop.style.left=`${Math.max(8,Math.min(innerWidth-360,r.left))}px`;pop.style.top=`${Math.max(8,r.top-pop.offsetHeight-8)}px`;setTimeout(()=>{const outside=e=>{if(!pop.contains(e.target)&&e.target!==anchor){close(pop);document.removeEventListener('pointerdown',outside)}};document.addEventListener('pointerdown',outside)},0)}
window.AUXY_EMOJI={COMMON,ALL,renderText,openPicker,normalize,img,isEmoji};
})();