const DEFAULT_MODEL='@cf/openai/gpt-oss-120b';
const FALLBACK_MODEL='@cf/meta/llama-3.3-70b-instruct-fp8-fast';
const MAX_MESSAGES=32,MAX_MESSAGE_CHARS=12000,MAX_TOTAL_CHARS=90000,MAX_TOOL_ROUNDS=2;
const SYSTEM_PROMPT=`تو Auxy AI هستی؛ یک دستیار فارسی سریع، باهوش و Gen Z داخل یک پلتفرم فیلم و سریال.
- قبل از پاسخ، منظور واقعی کاربر و context گفتگو را بفهم.
- برای گفت‌وگوی عادی از جستجوی کاتالوگ استفاده نکن.
- وقتی سؤال درباره فیلم، سریال، دراما، پیشنهاد، اثر مشابه، ژانر، بازیگر، رتبه یا مقایسه است از ابزار search_catalog استفاده کن.
- اگر ابزار داده داد، درباره عناوین فقط بر اساس همان داده‌ها ادعا کن.
- پاسخ را Markdown تمیز و طبیعی بنویس؛ برای پاسخ ساده کوتاه و برای موضوع پیچیده مفید و مرحله‌ای باش.
- لحن فارسی امروزی و Gen Z باشد، بدون اسلنگ مصنوعی یا cringe.
- اگر چیزی را نمی‌دانی صادقانه بگو.`;
function j(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store',...cors()}})}
function cors(){return {'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,authorization','access-control-max-age':'86400'}}
function norm(ms){const s=Array.isArray(ms)?ms:[];const out=s.filter(x=>x&&['user','assistant','system','tool'].includes(x.role)&&typeof x.content==='string'&&x.content.trim()).map(x=>({role:x.role,content:x.content.slice(0,MAX_MESSAGE_CHARS),...(x.role==='tool'&&x.name?{name:x.name}:{})})).slice(-MAX_MESSAGES);let t=out.reduce((n,x)=>n+x.content.length,0);while(t>MAX_TOTAL_CHARS&&out.length>4)t-=out.shift().content.length;return out}
function tool(){return {name:'search_catalog',description:'Search the Auxy movie and series catalog for recommendations, specific titles, similar works, genres, actors, ratings, Iranian movies/series, or comparisons. Return a small set of relevant results.',parameters:{type:'object',properties:{query:{type:'string',description:'Concise Persian or English catalog search query.'},limit:{type:'number',description:'1 to 12 results.'}},required:['query']}}}
async function catalog(env,request,query,limit=10){const q=String(query||'').trim().slice(0,180),n=Math.max(1,Math.min(Number(limit)||10,12));if(!q)return[];const h={apikey:env.SUPABASE_ANON_KEY,Authorization:request.headers.get('authorization')||`Bearer ${env.SUPABASE_ANON_KEY}`,'content-type':'application/json'};if(!env.SUPABASE_URL)return{error:'Supabase is not configured.'};try{const u=`${env.SUPABASE_URL}/rest/v1/rpc/auxy_ai_search_catalog`;const r=await fetch(u,{method:'POST',headers:h,body:JSON.stringify({p_query:q,p_limit:n})});if(r.ok){const d=await r.json();if(Array.isArray(d))return d.slice(0,n)}}catch(_){}return{error:'Catalog search failed.'}}
function calls(r){return Array.isArray(r?.tool_calls)?r.tool_calls:Array.isArray(r?.choices?.[0]?.message?.tool_calls)?r.choices[0].message.tool_calls:[]}
function cname(c){return String(c?.name||c?.function?.name||'')}
function cargs(c){const x=c?.arguments??c?.function?.arguments??{};if(x&&typeof x==='object')return x;try{return JSON.parse(String(x))}catch{return {}}}
function textof(r){if(typeof r?.response==='string')return r.response.trim();const x=r?.choices?.[0]?.message?.content;return typeof x==='string'?x.trim():''}
async function model(env,model,opts){if(!env.AI?.run)throw new Error('Workers AI binding AI is not available.');return env.AI.run(model,opts)}
async function run(env,opts){const primary=String(env.AUXY_AI_MODEL||DEFAULT_MODEL);try{return {model:primary,result:await model(env,primary,opts)}}catch(e){if(primary===FALLBACK_MODEL)throw e;return {model:FALLBACK_MODEL,result:await model(env,FALLBACK_MODEL,opts)}}}
async function ai(request,env){let body;try{body=await request.json()}catch{return j({error:'بدنه درخواست JSON معتبر نیست.'},400)}const conversation=norm(body?.messages);if(!conversation.length)return j({error:'پیام خالی است.'},400);let current=[{role:'system',content:SYSTEM_PROMPT},...conversation],movies=[],series=[],used=false,selected=env.AUXY_AI_MODEL||DEFAULT_MODEL,result=null;for(let round=0;round<MAX_TOOL_ROUNDS;round++){const r=await run(env,{messages:current,tools:[tool()],stream:false,max_tokens:Math.min(Math.max(Number(env.AUXY_AI_MAX_TOKENS)||2400,256),4096),temperature:.65,top_p:.95});selected=r.model;result=r.result;const tc=calls(result);if(!tc.length)break;used=true;for(const c of tc){if(cname(c)!=='search_catalog'){current.push({role:'tool',name:cname(c)||'unknown_tool',content:JSON.stringify({error:'Unknown tool'})});continue}const a=cargs(c),d=await catalog(env,request,a.query,a.limit);if(Array.isArray(d)){for(const x of d){if((x.media_type||x.content_kind||x.content_type)==='series'||x.media_type==='series')series.push(x);else movies.push(x)}}current.push({role:'tool',name:'search_catalog',content:JSON.stringify(d)})}}if(used){const fr=await run(env,{messages:current,stream:false,max_tokens:Math.min(Math.max(Number(env.AUXY_AI_MAX_TOKENS)||2400,256),4096),temperature:.65,top_p:.95});selected=fr.model;result=fr.result}return j({text:textof(result)||'یه لحظه ذهنم پرید 😅 دوباره بفرست.',movies:movies.slice(0,12),series:series.slice(0,12),model:selected,usedCatalogTool:used})}
async function artwork(env,url){const title=String(url.searchParams.get('title')||'').trim().slice(0,180),type=url.searchParams.get('type')==='series'?'series':'movie';if(!title)return j({error:'title is required'},400);const cache=await caches.default.match(url.toString());if(cache)return cache;let settings={artwork_provider:'cinemeta',custom_poster_template:null,custom_banner_template:null};try{if(env.SUPABASE_URL&&env.SUPABASE_ANON_KEY){const s=await fetch(`${env.SUPABASE_URL}/rest/v1/auxy_catalog_settings?id=eq.1&select=*`,{headers:{apikey:env.SUPABASE_ANON_KEY,Authorization:`Bearer ${env.SUPABASE_ANON_KEY}`}});if(s.ok){const d=await s.json();if(d[0])settings={...settings,...d[0]}}}}catch(_){}
let poster=null,background=null,imdb=null,provider=settings.artwork_provider||'cinemeta';const enc=encodeURIComponent(title);
try{if(provider==='custom'&&settings.custom_poster_template){poster=settings.custom_poster_template.replaceAll('{title}',enc)}else if(provider==='tvmaze'&&type==='series'){const r=await fetch(`https://api.tvmaze.com/singlesearch/shows?q=${enc}`);if(r.ok){const d=await r.json();poster=d?.image?.original||d?.image?.medium||null;if(d?.id){const ir=await fetch(`https://api.tvmaze.com/shows/${d.id}/images`);if(ir.ok){const imgs=await ir.json();const bg=imgs.find(x=>x?.type==='background')||imgs.find(x=>x?.type==='banner');background=bg?.resolutions?.original?.url||bg?.resolutions?.medium?.url||null}}}}}catch(_){}
try{if(!poster||!background){const sug=await fetch(`https://v3.sg.media-imdb.com/suggestion/titles/x/${enc}.json`);if(sug.ok){const d=await sug.json();const list=Array.isArray(d?.d)?d.d:[];const q=title.toLowerCase();const best=list.find(x=>String(x?.l||'').toLowerCase()===q)||list[0];imdb=best?.id||null;if(!poster)poster=best?.i?.imageUrl||null}}}catch(_){}
try{if(imdb&&provider!=='custom'){const r=await fetch(`https://v3-cinemeta.strem.io/meta/${type}/${imdb}.json`);if(r.ok){const d=await r.json();const m=d?.meta||d;if(!poster)poster=m?.poster||null;background=m?.background||m?.poster||null}}}catch(_){}
if(!background)background=poster;if(provider==='custom'&&settings.custom_banner_template)background=settings.custom_banner_template.replaceAll('{title}',enc);const payload=j({title,poster,background,imdb_id:imdb,provider});payload.headers.set('cache-control','public, max-age=86400');caches.default.put(url.toString(),payload.clone());return payload}
export default{async fetch(request,env){const u=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:cors()});if(u.pathname==='/api/health')return j({ok:true,ai:Boolean(env.AI?.run),model:env.AUXY_AI_MODEL||DEFAULT_MODEL,movieSearch:Boolean(env.SUPABASE_URL&&env.SUPABASE_ANON_KEY)});if(u.pathname==='/api/ai'){if(request.method!=='POST')return j({error:'Method not allowed'},405);try{return await ai(request,env)}catch(e){return j({error:`Workers AI error: ${e?.message||String(e)}`},500)}}if(u.pathname==='/api/artwork')return artwork(env,u);return env.ASSETS.fetch(request)}};
